### PR TITLE
Change the domain name

### PR DESCRIPTION
**Pull request by fabpot**
As we are moving from using sensiolabs.org for Open-Source projects, I'd like to move cs.sensiolabs.org to cs.symfony.com.

### CODE REVIEW

**Comment by fabpot** [comment]
DNS changes have been done, so should work right away after a merge.

**Comment by fabpot** [comment]
The website listed on https://github.com/FriendsOfPHP/PHP-CS-Fixer should be changed as well when it's done.

**Comment by keradus** [comment]
would cs.sensiolabs.org redirect to cs.symfony.org , @fabpot ?

**Comment by fabpot** [comment]
Yes, that's the goal indeed.

**Comment by keradus** [comment]
awesome ;)
I'm on holidays right now. Before merging I would like to double check if there are other places where we need to update the URL (eg, self-update command, probably). Let me do that in next week, sounds good ?

**Comment by nicolas-grekas** [comment]
the link in the github description should be changed also while merging

**Comment by keradus** [comment]
Thank you, @fabpot

**Comment by keradus** [comment]
Thank you, @fabpot 
can you please redirect cs.sensiolabs.org to cs.symfony.com 
also, is it possible to enable ssl for it ?

**Comment by keradus** [comment]
works like a charm, thank you ;)

**Pull request merged**
